version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.11"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs

mkdocs:
  config_file: docs/mkdocs.yml
  fail_on_warning: false

formats:
  - pdf
  - epub

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - docs 